### ISSUE TITLE
Add link to https://cukebuild.net to the GitHub repo

### ISSUE THREAD

**Issue by augustoproiete** [bjorkstromm/cukebuild#3]
There's no easy way to go to the website from the GitHub repo

![image](https://user-images.githubusercontent.com/177608/113317872-3983bb80-92e6-11eb-8075-bee24299aef9.png)

**Comment by bjorkstromm** [comment]
Fixed! Thanks!

![image](https://user-images.githubusercontent.com/7863439/113328770-6c00d900-9325-11eb-889d-5789f1ad33c6.png)
